#!/usr/bin/env bash
# build-extensions.sh — materialize the Chrome & Firefox extension folders
# from the shared engine + vendored runtime. Run from the repo root:
#   scripts/build-extensions.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHARED="$ROOT/extension/_shared"
ENGINE_SRC="$ROOT/server/static/js/engine"
ORT_SRC="$ROOT/server/static/ort"
JS_SRC="$ROOT/server/static/js"

copy_engine() { # $1 = extension dir
  local ext="$1"
  mkdir -p "$ext/engine" "$ext/vendor/ort" "$ext/vendor/models" "$ext/icons"
  for f in geometry.js pii-rules.js yunet.js extractor.js renderer.js vision-engine.js gateway.js client.js; do
    cp "$ENGINE_SRC/$f" "$ext/engine/$f"
  done
  cp "$JS_SRC/ort.all.min.js" "$ext/vendor/ort/ort.all.min.js"
  cp "$ORT_SRC/ort-wasm-simd-threaded.wasm" "$ORT_SRC/ort-wasm-simd-threaded.jsep.wasm" \
     "$ORT_SRC/ort-wasm-simd-threaded.mjs"  "$ORT_SRC/ort-wasm-simd-threaded.jsep.mjs" "$ext/vendor/ort/"
  cp "$ROOT/server/static/models/yunet.onnx" "$ext/vendor/models/yunet.onnx"
  cp "$SHARED/content.js" "$SHARED/popup.html" "$SHARED/popup.js" "$ext/"
  cp "$ROOT/extension/chrome/icons"/icon*.png "$ext/icons/" 2>/dev/null || true
  echo "built: $ext"
}

copy_engine "$ROOT/extension/chrome"
copy_engine "$ROOT/extension/firefox"

# Firefox page-world gateway bundle (MV2 has no chrome.scripting):
# gateway.js is self-contained (its own PII patterns), so the bundle is
# just the gateway source + an auto-enable bootstrap.
{
  echo "/* generated by scripts/build-extensions.sh — do not edit */"
  echo "'use strict';"
  cat "$ENGINE_SRC/gateway.js"
  cat <<'BOOT'
;(function () {
  try {
    if (window.PVA && window.PVA.Gateway && !window.__PVA_PAGE_GATEWAY__) {
      window.__PVA_PAGE_GATEWAY__ = new window.PVA.Gateway.PrivacyGateway();
      window.__PVA_PAGE_GATEWAY__.enable();
    }
  } catch (e) {}
})();
BOOT
} > "$ROOT/extension/firefox/main-gateway-bundle.js"
echo "built: main-gateway-bundle (firefox)"
echo "done."
